### ISSUE TITLE
Inconsistency between code and documentation

### ISSUE THREAD

**Issue by rvo1994** [cumulio/cumul.io-sdk-python#12]
https://github.com/cumulio/cumul.io-sdk-python/blob/f717cfca55246a14372c98bcd27f054aac77f543/cumulio/cumulio.py#L53

According to the [documentation](https://developer.cumul.io/#associate), the associate method has the following parameters:

```
client.associate("resource_name", "<your_resource_name_id>", {"role":"<resource to link name>","id":"<resource entity id>"}, {
    "property name": "<property value>"
} )
```

However when I use this syntax I get the following error:
```
TypeError: associate() missing 1 required positional argument: 'association_id'
```

I looked at the code and I see that _association_role_ and _association_id_ parameters should not be provided inside a dictionary but as separate parameters. 

Could you please align the doc with the code ?

**Comment by carmenvandeloo** [comment]
Hi @rvo1994 , thanks for flagging that! I have updated our documentation.
