### ISSUE TITLE
Support to set apiServer

### ISSUE THREAD

**Issue by carmenvandeloo** [cumulio/cumul.io-sdk-python#5]
Hi! 

It would be great if the Python SDK would also support the setting of the apiServer, right now it is hardcoded to https://api.cumul.io. Clients with a VPC or working on the US multitenant environment should be able to override it.

**Comment by TuanaCelik** [comment]
Just pushed a newer version where there's an optional 'api_host'. If not provided it defaults to  https://api.cumul.io again. Published to pypi too: https://pypi.org/project/cumulio/
Let me know if there are further issues.
