### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by hugoduportet** [cumulio/cumul.io-sdk-python#8]
The exception is not cashed properly here:
https://github.com/cumulio/cumul.io-sdk-python/blob/a3c14555fb0840910cd5a1da345644496586471e/cumulio/cumulio.py#L88

I encounter this problem when the value of any of the properties field is not the expected one:

For exemple:

{
   "action":"update",
   "id":"a630d5dd-396e-461e-92df-76aa2d0279fa",
   "key":"a7cac872-9bcd-4731-8dec-1c7eb5435f32",
   "properties":{
      "updates":[
         {
            "children":"[]",
            "color":"'#072448'",
            "id":"<SOME_BAD_INPUT>",
            "name":"{'nl': <SOME_BAD_INPUT>, 'fr': <SOME_BAD_INPUT>, 'en': <SOME_BAD_INPUT>}",
            "order_index":"None",
            "trace":"['', <SOME_BAD_INPUT>]",
            "tree_order_index":"None",
            "virtual":"False"
         }
      ]
   },
   "token":"$CUMUL_TOKEN",
   "version":"0.1.0"
}

**Comment by TuanaCelik** [comment]
@hugoduportet I am looking into this now, thank you for flagging

**Comment by TuanaCelik** [comment]
@hugoduportet Just released a patch version (0.2.2) which should hopefully fix this. My bad, the if statement was in a silly place :) 
Let me know and I'll close the issue if all good

**Comment by hugoduportet** [comment]
Yes, thanks a lot !
