### ISSUE TITLE
Using proxies

### ISSUE THREAD

**Issue by Jkarioun** [cumulio/cumul.io-sdk-python#9]
Current version doesn't support proxies for the POST requests

**Comment by TuanaCelik** [comment]
Thanks, I will merge the PR and release a new version of the SDK :)

**Comment by TuanaCelik** [comment]
@Jkarioun  - I've just released a new version: 0.2.3 with your changes. I've also changed the repo a bit and now we have a Contributing.md file separate from the Readme 🙂 - so thank you for inspiring that!
